# Generated by Django 4.1.13 on 2025-02-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_school', '0002_remove_parent_email_remove_parent_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Set to Active to approve the teacher', max_length=10),
        ),
    ]
