# Generated by Django 4.1.5 on 2023-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_school", "0004_assignment_created_by_alter_subject_exam_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sciences", "Sciences"),
                    ("arts", "Arts"),
                    ("commerce", "Commerce"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
